//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Skills { get; set; }
        public string Salary { get; set; }
        public string Join_Date { get; set; }
        public string Reporting_Person { get; set; }
        public int Status { get; set; }
    }
}
